version: '3'
services:

  db:
    restart: on-failure
    platform: linux/x86_64
    image: "mysql:5.6"
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin

#  php:
#    restart: on-failure
#    build: .
#    volumes:
#      - ".:/var/www/html"
#    ports:
#      - 8080:80
#    environment:
#      DB_PASSWORD: admin
#      DB_NAME: admin
#      DB_USER: admin
#      DB_HOST: db
